### ISSUE TITLE
Styling To-Do's

### ISSUE THREAD

**Issue by kx-shi** [kx-shi/TrailSeeker#22]
- [ ] Add hover to push in comment form
- [ ] Add styling to inside comment form (where you write)
- [ ] Make comment push-button equal width as comment text input block
- [ ] Adjust spacing between heart and trail name for trail cards
- [ ] Make site nicer looking for smaller screens than desktop
- [ ] Change icons in trail 'general information' block to look more consistent
- [ ] Add icon of trail type in 'general information'
